name: Dependency Checks
on:
  pull_request:
    paths:
        - 'project/gh-action/**'
  push:
    branches:
        - main
    paths:
        - 'project/gh-action/**'

jobs:


  java:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: project/gh-action/java
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Check dependencies
        run: mvn dependency:resolve