name: Infrastructure Validation
on:
  pull_request:
    paths:
        - 'project/gh-action/**'
  push:
    branches:
        - main
    paths:
        - 'project/gh-action/**'

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: project/gh-action/infrastructure/kubernetes
    steps:
      - uses: actions/checkout@v4
      
      - name: Install kubeconform
        run: |
          wget https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar xf kubeconform-linux-amd64.tar.gz
          sudo mv kubeconform /usr/local/bin/
      
      - name: Validate K8s manifests
        run: kubeconform --kubernetes-version 1.24.0 -strict *.yaml

  terraform:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: project/gh-action/infrastructure/terraform
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Validate Terraform
        run: |
          terraform init
          terraform validate